"""Invoice text helpers.

The Macedonian amount-in-words used to be generated by an LLM. It is now computed
deterministically: the value printed in words on an invoice must match the digits beside
it, and an LLM offered no way to guarantee or verify that. The replacement is offline,
instant, free, and round-trip verifiable (see `macedonian_numbers.words_to_int`).
"""

from __future__ import annotations

from decimal import Decimal

from services.invoices.macedonian_numbers import amount_to_words

MAX_TEXT_LENGTH = 255


def amount_to_macedonian_text(amount: Decimal | float | str) -> str:
    """Convert a monetary amount to a Macedonian textual money phrase.

    Accepts float because callers read it off a Pydantic model; converted via `str` so a
    value like 14250.5 does not pick up binary floating-point artefacts on the way in.
    """
    value = amount if isinstance(amount, Decimal) else Decimal(str(amount))
    text = amount_to_words(value)

    if not text:
        raise RuntimeError("Macedonian amount text conversion produced an empty string.")

    # The invoices.price_after_tax_text column is capped at 255 characters. The cap is
    # unreachable for supported amounts, so exceeding it means something upstream changed.
    if len(text) > MAX_TEXT_LENGTH:
        raise RuntimeError(f"Macedonian amount text exceeds {MAX_TEXT_LENGTH} characters: {len(text)}")

    return text
